
import Web3Provider from '@/components/utils/Web3Provider'
import './css/style.css'

import { Inter, Playfair_Display } from 'next/font/google'
import toast, { Toaster } from 'react-hot-toast';


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
        <body className={`${inter.variable} ${playfair.variable} font-inter antialiased bg-slate-100 text-slate-800 tracking-tight`}>
          
            <Web3Provider>
                {children}
            </Web3Provider>
            <Toaster />
        </body>
        
      
    </html>
  )
}
